# Code adapted from: https://github.com/shahafp/TRC-Hebrew

from .temporal_relation_classification import TemporalRelationClassification
from .temporal_relation_classification_config import TemporalRelationClassificationConfig
from .temporal_relation_classification_pipeline import TemporalRelationClassificationPipeline
